# Generated by Django 6.0.2 on 2026-02-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('country_code', models.CharField(default='91', max_length=5)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
